project_id = "njxxqdcwvehlvqufuyww"

[functions.create-user-with-invite]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.invoice-ocr]
verify_jwt = true

[functions.password-reset]
verify_jwt = false

[functions.password-verification-hook]
verify_jwt = false