project_id = "njxxqdcwvehlvqufuyww"

[functions.create-user-with-invite]
verify_jwt = true

[functions.invite-client-user]
verify_jwt = true

[functions.notify-portal-proposal]
verify_jwt = true

[functions.portal-reset-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.invoice-ocr]
verify_jwt = true

[functions.password-reset]
verify_jwt = false

[functions.password-verification-hook]
verify_jwt = false

[functions.update-overdue-status]
verify_jwt = false

[functions.send-user-access-email]
verify_jwt = true

[functions.notify-internal-change-request]
verify_jwt = true