-- Reclassificação em massa do catálogo (254 itens). Fonte: planilha revisada item a item.
-- term_id é fonte da verdade; resolvido por nome via JOIN (após renomeações canônicas abaixo).
-- 26 itens de exclusão já arquivados em migration anterior; não constam aqui.

-- 1) Renomeações canônicas de subcategoria (preserva term_id e referências).
UPDATE public.taxonomy_terms SET name='Cafés & Chás'            WHERE id='b3b1162f-89b9-41a0-bf93-7cbe74397394';
UPDATE public.taxonomy_terms SET name='Cozinha'                 WHERE id='96420ad8-a386-4399-a141-c4341eb5820e';
UPDATE public.taxonomy_terms SET name='Descartáveis Higiênicos' WHERE id='a1b2c3d4-4444-4000-a000-000000000053';
UPDATE public.taxonomy_terms SET name='Outros'                  WHERE id='66aaeedd-c03e-4588-a884-2c474f878838';

-- 2) Reclassificação. type_term_id/category_term_id/subcategory_term_id resolvidos por nome.
WITH src(code,tipo,cat,sub,unc,unu) AS (VALUES
('MAT00129','Insumo','Alimentos & Ingredientes','Açúcares & Adoçantes','kg','g'),
('MAT00082','Insumo','Alimentos & Ingredientes','Açúcares & Adoçantes','kg','g'),
('MAT00011','Insumo','Alimentos & Ingredientes','Açúcares & Adoçantes','kg','g'),
('MAT00088','Insumo','Alimentos & Ingredientes','Líquidos Base','L','mL'),
('MAT00240','Insumo','Alimentos & Ingredientes','Hortifruti','un','g'),
('MAT00117','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00114','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00083','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00200','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00107','Insumo','Alimentos & Ingredientes','Óleos & Gorduras','L','mL'),
('MAT00244','Insumo','Alimentos & Ingredientes','Conservas & Enlatados','kg','g'),
('MAT00094','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00015','Insumo','Alimentos & Ingredientes','Panificados','kg','g'),
('MAT00024','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00218','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00246','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00197','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00259','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00018','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00079','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00002','Insumo','Alimentos & Ingredientes','Panificados','pacote','un'),
('MAT00063','Insumo','Alimentos & Ingredientes','Panificados','pacote','un'),
('MAT00078','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00087','Insumo','Alimentos & Ingredientes','Grãos & Cereais','pacote','g'),
('MAT00034','Insumo','Alimentos & Ingredientes','Grãos & Cereais','pacote','g'),
('MAT00275','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00149','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','un','g'),
('MAT00058','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00007','Insumo','Alimentos & Ingredientes','Conservas & Enlatados','kg','g'),
('MAT00224','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00203','Material de Consumo','Operacionais','Combustíveis','kg','kg'),
('MAT00096','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00146','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00108','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00212','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00121','Insumo','Bebidas','Bebidas Alcoólicas','un','mL'),
('MAT00192','Produto de Revenda','Bebidas','Cafés & Chás','L','mL'),
('MAT00208','Produto de Revenda','Bebidas','Cafés & Chás','L','mL'),
('MAT00229','Insumo','Alimentos & Ingredientes','Laticínios','L','mL'),
('MAT00238','Insumo','Alimentos & Ingredientes','Conservas & Enlatados','kg','g'),
('MAT00214','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','un','g'),
('MAT00164','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','un','g'),
('MAT00046','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','un','g'),
('MAT00255','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','un','g'),
('MAT00084','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','un','g'),
('MAT00254','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','un','g'),
('MAT00256','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','un','g'),
('MAT00220','Insumo','Alimentos & Ingredientes','Grãos & Cereais','un','g'),
('MAT00071','Insumo','Alimentos & Ingredientes','Grãos & Cereais','un','g'),
('MAT00076','Insumo','Doces & Confeitaria','Doces Finos','un','g'),
('MAT00099','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00075','Insumo','Doces & Confeitaria','Recheios & Coberturas','un','mL'),
('MAT00205','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00249','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00016','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00223','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00160','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','un','g'),
('MAT00049','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00186','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00062','Produto de Revenda','Salgados','Salgados Assados','pacote','un'),
('MAT00027','Insumo','Alimentos & Ingredientes','Grãos & Cereais','un','g'),
('MAT00069','Material de Consumo','Operacionais','Outros','L','g'),
('MAT00053','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00231','Insumo','Alimentos & Ingredientes','Óleos & Gorduras','kg','g'),
('MAT00252','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','un','mL'),
('MAT00236','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00001','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00122','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00050','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00105','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00097','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00230','Insumo','Alimentos & Ingredientes','Óleos & Gorduras','kg','g'),
('MAT00026','Insumo','Doces & Confeitaria','Recheios & Coberturas','kg','g'),
('MAT00166','Insumo','Doces & Confeitaria','Recheios & Coberturas','kg','g'),
('MAT00191','Insumo','Doces & Confeitaria','Recheios & Coberturas','kg','g'),
('MAT00037','Insumo','Doces & Confeitaria','Recheios & Coberturas','kg','g'),
('MAT00128','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00189','Insumo','Alimentos & Ingredientes','Óleos & Gorduras','kg','g'),
('MAT00183','Insumo','Doces & Confeitaria','Recheios & Coberturas','kg','g'),
('MAT00059','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00077','Insumo','Alimentos & Ingredientes','Cacau & Chocolate','kg','g'),
('MAT00202','Produto de Revenda','Bebidas','Refrigerantes','L','mL'),
('MAT00023','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00081','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00019','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00010','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00051','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00044','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00248','Material de Consumo','Operacionais','Combustíveis','kg','kg'),
('MAT00086','Produto Intermediário','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00048','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00091','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00036','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00250','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00066','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00047','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00194','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','un','g'),
('MAT00181','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00009','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00215','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00021','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00038','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00221','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00199','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00110','Insumo','Doces & Confeitaria','Recheios & Coberturas','kg','g'),
('MAT00012','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00196','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00260','Insumo','Alimentos & Ingredientes','Panificados','kg','g'),
('MAT00209','Insumo','Alimentos & Ingredientes','Panificados','kg','un'),
('MAT00190','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00148','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','un','g'),
('MAT00120','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','un','mL'),
('MAT00092','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00013','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00219','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00014','Insumo','Alimentos & Ingredientes','Laticínios','un','g'),
('MAT00025','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00239','Insumo','Alimentos & Ingredientes','Óleos & Gorduras','un','mL'),
('MAT00006','Insumo','Alimentos & Ingredientes','Proteínas','un','un'),
('MAT00198','Insumo','Alimentos & Ingredientes','Panificados','kg','g'),
('MAT00278','Insumo','Alimentos & Ingredientes','Panificados','un','g'),
('MAT00245','Insumo','Alimentos & Ingredientes','Panificados','un','g'),
('MAT00247','Produto de Revenda','Salgados','Salgados Assados','pacote','un'),
('MAT00057','Insumo','Alimentos & Ingredientes','Panificados','un','g'),
('MAT00204','Insumo','Alimentos & Ingredientes','Panificados','kg','g'),
('MAT00101','Insumo','Alimentos & Ingredientes','Panificados','un','g'),
('MAT00241','Insumo','Alimentos & Ingredientes','Panificados','un','g'),
('MAT00235','Insumo','Alimentos & Ingredientes','Panificados','un','g'),
('MAT00242','Material de Consumo','Operacionais','Utensílios','fardo','un'),
('MAT00172','Material de Consumo','Operacionais','Utensílios','fardo','un'),
('MAT00118','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00028','Insumo','Alimentos & Ingredientes','Conservas & Enlatados','kg','g'),
('MAT00093','Insumo','Alimentos & Ingredientes','Conservas & Enlatados','kg','g'),
('MAT00100','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00225','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00158','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00174','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00251','Insumo','Alimentos & Ingredientes','Conservas & Enlatados','kg','g'),
('MAT00115','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00173','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00102','Insumo','Alimentos & Ingredientes','Conservas & Enlatados','kg','g'),
('MAT00116','Insumo','Alimentos & Ingredientes','Conservas & Enlatados','kg','g'),
('MAT00261','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00237','Insumo','Alimentos & Ingredientes','Grãos & Cereais','kg','g'),
('MAT00180','Produto Acabado','Doces & Confeitaria','Sobremesas','un','un'),
('MAT00169','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00178','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00226','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00161','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00032','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00098','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00104','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00065','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00103','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00067','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00265','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00031','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00095','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00052','Insumo','Alimentos & Ingredientes','Panificados','pacote','g'),
('MAT00003','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00176','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00040','Insumo','Alimentos & Ingredientes','Laticínios','kg','g'),
('MAT00043','Insumo','Alimentos & Ingredientes','Hortifruti','un','g'),
('MAT00112','Produto de Revenda','Alimentos & Ingredientes','Açúcares & Adoçantes','caixa','un'),
('MAT00106','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00109','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','kg','g'),
('MAT00041','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00004','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00206','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00147','Insumo','Alimentos & Ingredientes','Proteínas','un','g'),
('MAT00201','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00193','Produto de Revenda','Bebidas','Sucos & Néctares','un','mL'),
('MAT00061','Produto de Revenda','Bebidas','Sucos & Néctares','un','mL'),
('MAT00228','Produto de Revenda','Bebidas','Sucos & Néctares','un','mL'),
('MAT00170','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00145','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00017','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00008','Insumo','Alimentos & Ingredientes','Hortifruti','kg','g'),
('MAT00207','Insumo','Alimentos & Ingredientes','Proteínas','kg','g'),
('MAT00080','Insumo','Alimentos & Ingredientes','Condimentos & Temperos','un','mL'),
('MAT00195','Insumo','Alimentos & Ingredientes','Panificados','pacote','g'),
('MAT00182','Produto de Revenda','Bebidas','Águas','un','un'),
('MAT00188','Produto de Revenda','Bebidas','Águas','un','un'),
('MAT00157','Produto de Revenda','Bebidas','Cafés & Chás','un','un'),
('MAT00140','Produto Acabado','Bebidas','Cafés & Chás','mL','mL'),
('MAT00211','Produto de Revenda','Bebidas','Cafés & Chás','L','mL'),
('MAT00277','Produto de Revenda','Bebidas','Bebidas Alcoólicas','un','un'),
('MAT00056','Produto de Revenda','Bebidas','Refrigerantes','L','mL'),
('MAT00184','Produto de Revenda','Bebidas','Refrigerantes','L','mL'),
('MAT00035','Produto de Revenda','Bebidas','Sucos & Néctares','un','un'),
('MAT00039','Produto de Revenda','Bebidas','Sucos & Néctares','un','un'),
('MAT00020','Produto de Revenda','Bebidas','Sucos & Néctares','un','un'),
('MAT00271','Produto Acabado','Doces & Confeitaria','Bolos & Tortas','un','un'),
('MAT00141','Produto Intermediário','Doces & Confeitaria','Recheios & Coberturas','g','g'),
('MAT00142','Produto Acabado','Doces & Confeitaria','Bolos & Tortas','un','un'),
('MAT00143','Produto Acabado','Doces & Confeitaria','Bolos & Tortas','un','un'),
('MAT00127','Produto Acabado','Doces & Confeitaria','Bolos & Tortas','un','un'),
('MAT00133','Produto Acabado','Doces & Confeitaria','Bolos & Tortas','un','un'),
('MAT00165','Produto Intermediário','Doces & Confeitaria','Recheios & Coberturas','g','g'),
('MAT00130','Produto Intermediário','Doces & Confeitaria','Recheios & Coberturas','g','g'),
('MAT00134','Produto Intermediário','Doces & Confeitaria','Massas & Bases','g','g'),
('MAT00131','Produto Intermediário','Doces & Confeitaria','Massas & Bases','g','g'),
('MAT00136','Produto Intermediário','Doces & Confeitaria','Massas & Bases','g','g'),
('MAT00153','Produto Intermediário','Doces & Confeitaria','Massas & Bases','g','g'),
('MAT00280','Produto Intermediário','Doces & Confeitaria','Massas & Bases','g','g'),
('MAT00125','Produto Intermediário','Doces & Confeitaria','Massas & Bases','g','g'),
('MAT00270','Produto Acabado','Doces & Confeitaria','Bolos & Tortas','un','un'),
('MAT00276','Produto Acabado','Doces & Confeitaria','Doces Finos','un','un'),
('MAT00163','Produto Intermediário','Doces & Confeitaria','Recheios & Coberturas','g','g'),
('MAT00132','Produto Intermediário','Doces & Confeitaria','Recheios & Coberturas','g','g'),
('MAT00263','Produto Intermediário','Doces & Confeitaria','Recheios & Coberturas','g','g'),
('MAT00126','Produto Intermediário','Doces & Confeitaria','Recheios & Coberturas','g','g'),
('MAT00268','Embalagem','Embalagem','Embalagens Secundárias','un','un'),
('MAT00267','Embalagem','Embalagem','Embalagens Secundárias','un','un'),
('MAT00074','Embalagem','Embalagem','Embalagens Secundárias','un','un'),
('MAT00073','Embalagem','Embalagem','Embalagens Primárias','un','un'),
('MAT00113','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00257','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00258','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00253','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00070','Embalagem','Embalagem','Embalagens Primárias','un','un'),
('MAT00033','Material de Consumo','Operacionais','Utensílios','caixa','un'),
('MAT00234','Material de Consumo','Operacionais','Utensílios','un','un'),
('MAT00233','Material de Consumo','Operacionais','Utensílios','un','un'),
('MAT00162','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00072','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00111','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00005','Embalagem','Embalagem','Embalagens Primárias','pacote','un'),
('MAT00243','Embalagem','Embalagem','Embalagens Secundárias','pacote','un'),
('MAT00089','Embalagem','Embalagem','Descartáveis','pacote','un'),
('MAT00029','Equipamento','Equipamentos','Cozinha','un','un'),
('MAT00064','Equipamento','Operacionais','Utensílios','un','un'),
('MAT00185','Equipamento','Equipamentos','Serviço','un','un'),
('MAT00055','Material de Consumo','Higiene e Limpeza','Desinfetantes & Sanitizantes','un','mL'),
('MAT00139','Material de Consumo','Higiene e Limpeza','Desinfetantes & Sanitizantes','un','mL'),
('MAT00187','Material de Consumo','Higiene e Limpeza','Detergentes & Sabões','un','mL'),
('MAT00054','Material de Consumo','Higiene e Limpeza','Descartáveis Higiênicos','pacote','un'),
('MAT00279','Equipamento','Operacionais','Infraestrutura','un','un'),
('MAT00262','Material de Consumo','Operacionais','Combustíveis','L','L'),
('MAT00269','Material de Consumo','Operacionais','Outros','caixa','un'),
('MAT00135','Produto Intermediário','Doces & Confeitaria','Massas & Bases','g','g'),
('MAT00085','Produto Intermediário','Doces & Confeitaria','Massas & Bases','g','g'),
('MAT00138','Produto de Revenda','Salgados','Salgados Assados','pacote','un'),
('MAT00124','Produto Acabado','Salgados','Sanduíches','un','un'),
('MAT00171','Produto Acabado','Salgados','Tortinhas & Quiches','un','un'),
('MAT00272','Produto Intermediário','Salgados','Massas & Bases','g','g'),
('MAT00150','Produto Intermediário','Salgados','Massas & Bases','g','g'),
('MAT00264','Produto Acabado','Salgados','Salgados Assados','un','un'),
('MAT00151','Produto Intermediário','Salgados','Sanduíches','un','un'),
('MAT00274','Produto Acabado','Salgados','Salgados Assados','un','un'),
('MAT00144','Produto Acabado','Salgados','Tortinhas & Quiches','un','un'),
('MAT00273','Produto Intermediário','Salgados','Molhos & Recheios','g','g'),
('MAT00123','Produto Acabado','Salgados','Sanduíches','un','un'),
('MAT00266','Produto Acabado','Salgados','Sanduíches','un','un')
),
tdef AS (SELECT key,id FROM public.taxonomy_definitions),
tmap(tipo,legacy) AS (VALUES
 ('Insumo','ingredient'),('Embalagem','packaging'),('Produto Intermediário','intermediate_product'),
 ('Produto Acabado','finished_product'),('Produto Composto','composite_product'),
 ('Produto de Revenda','resale_product'),('Material de Limpeza','supply'),
 ('Material de Consumo','supply'),('Equipamento','equipment'))
UPDATE public.materials m SET
  material_type       = tmap.legacy,
  type_term_id        = tt.id,
  category            = s.cat,
  category_term_id    = ct.id,
  subcategory         = NULLIF(s.sub,''),
  subcategory_term_id = st.id,
  purchase_unit       = s.unc,
  usage_unit          = s.unu,
  updated_at          = now()
FROM src s
JOIN tmap ON tmap.tipo = s.tipo
JOIN public.taxonomy_terms tt ON tt.name=s.tipo AND tt.taxonomy_id=(SELECT id FROM tdef WHERE key='material_type')
JOIN public.taxonomy_terms ct ON ct.name=s.cat AND ct.taxonomy_id=(SELECT id FROM tdef WHERE key='material_category') AND ct.is_active
LEFT JOIN public.taxonomy_terms st ON NULLIF(s.sub,'') IS NOT NULL AND st.name=s.sub
     AND st.taxonomy_id=(SELECT id FROM tdef WHERE key='material_subcategory') AND st.parent_id=ct.id AND st.is_active
WHERE m.code=s.code;
