// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njxxqdcwvehlvqufuyww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qeHhxZGN3dmVobHZxdWZ1eXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjgzMzAsImV4cCI6MjA3NDIwNDMzMH0.IlS_EBzrNr2i2gqd9zRGL75YK4PYr3QGIsjslfuipwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});