import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';

interface Client {
  id: string;
  name: string;
}

interface ProposalFormData {
  client_id: string;
  event_category: string;
  event_date: string;
  number_of_people: number;
  target_weight_per_person: number;
  notes?: string;
}

interface Props {
  onSuccess: () => void;
  onCancel: () => void;
}

const eventCategories = [
  'Coffee Break',
  'Brunch', 
  'Coquetel',
  'Almoco',
  'Jantar',
  'Festa Infantil',
  'Casamento',
  'Reuniao Corporativa'
];

export default function ProposalForm({ onSuccess, onCancel }: Props) {
  const [loading, setLoading] = useState(false);
  const [clients, setClients] = useState<Client[]>([]);

  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm<ProposalFormData>({
    defaultValues: {
      target_weight_per_person: 200
    }
  });

  const watchedValues = watch();
  const totalTargetWeight = (watchedValues.number_of_people || 0) * (watchedValues.target_weight_per_person || 200);

  useEffect(() => {
    loadClients();
  }, []);

  const loadClients = async () => {
    try {
      const { data, error } = await supabase
        .from('clients')
        .select('id, name')
        .eq('status', 'Ativo')
        .order('name');

      if (error) throw error;
      setClients(data || []);
    } catch (error) {
      console.error('Erro ao carregar clientes:', error);
      toast.error('Erro ao carregar clientes');
    }
  };

  const onSubmit = async (data: ProposalFormData) => {
    try {
      setLoading(true);

      // The proposal_number is auto-generated by database trigger
      // Don't include it in the insert
      const proposalData = {
        client_id: data.client_id,
        event_category: data.event_category,
        event_date: data.event_date || null,
        number_of_people: data.number_of_people,
        target_weight_per_person: data.target_weight_per_person,
        total_weight: 0,
        total_amount: 0,
        notes: data.notes || null,
        status: 'Rascunho'
      };

      const { error } = await supabase
        .from('proposals')
        .insert(proposalData as any);

      if (error) throw error;

      toast.success('Proposta criada com sucesso!');
      onSuccess();
    } catch (error) {
      console.error('Erro ao salvar proposta:', error);
      toast.error('Erro ao salvar proposta');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Nova Proposta</CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="client_id">Cliente *</Label>
              <Select onValueChange={(value) => setValue('client_id', value)}>
                <SelectTrigger>
                  <SelectValue placeholder="Selecione o cliente" />
                </SelectTrigger>
                <SelectContent>
                  {clients.filter(client => client.id && client.id.trim() !== '').map(client => (
                    <SelectItem key={client.id} value={client.id}>
                      {client.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.client_id && <span className="text-sm text-destructive">Campo obrigatório</span>}
            </div>

            <div>
              <Label htmlFor="event_category">Categoria do Evento *</Label>
              <Select onValueChange={(value) => setValue('event_category', value)}>
                <SelectTrigger>
                  <SelectValue placeholder="Selecione a categoria" />
                </SelectTrigger>
                <SelectContent>
                  {eventCategories.filter(category => category && category.trim() !== '').map(category => (
                    <SelectItem key={category} value={category}>
                      {category}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.event_category && <span className="text-sm text-destructive">Campo obrigatório</span>}
            </div>

            <div>
              <Label htmlFor="event_date">Data do Evento</Label>
              <Input
                type="date"
                autoComplete="off"
                {...register('event_date')}
              />
            </div>

            <div>
              <Label htmlFor="number_of_people">Número de Pessoas *</Label>
              <Input
                type="number"
                min="1"
                autoComplete="off"
                {...register('number_of_people', { required: true, min: 1 })}
              />
              {errors.number_of_people && <span className="text-sm text-destructive">Campo obrigatório</span>}
            </div>

            <div>
              <Label htmlFor="target_weight_per_person">Peso por Pessoa (g) *</Label>
              <Input
                type="number"
                min="50"
                autoComplete="off"
                {...register('target_weight_per_person', { required: true, min: 50 })}
              />
              {errors.target_weight_per_person && <span className="text-sm text-destructive">Mínimo 50g</span>}
            </div>

            <div>
              <Label>Peso Total Alvo</Label>
              <Input
                value={`${totalTargetWeight}g`}
                disabled
                className="bg-muted"
              />
            </div>
          </div>

          <div>
            <Label htmlFor="notes">Observações</Label>
            <Textarea
              {...register('notes')}
              rows={3}
              placeholder="Observações sobre o evento..."
            />
          </div>

          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" onClick={onCancel}>
              Cancelar
            </Button>
            <Button type="submit" disabled={loading}>
              {loading ? 'Salvando...' : 'Criar Proposta'}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}